import React from 'react'
import type { Metadata } from 'next'
import { Header } from '@/components/ui/Header'
import { SideBar } from '@/components/ui/SideBar'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
            <SideBar />
            <div className="flex flex-col">
                <Header />
                {children}
            </div>
        </div>
    )
}
